Repository cloud-native-toolkit/terraform-cp4i-dependency-management, pull requests merged in 2022-01, with the labels that each got.

#1 Adds configuration for platform navigator
  .github/scripts/validate-deploy.sh
  README.md
  main.tf
  module.yaml
  outputs.tf
  test/stages/stage1-cluster.tf
  test/stages/stage1-namespaces.tf
  test/stages/stage1-olm.tf
  test/stages/stage1b-capture-state.tf
  test/stages/stage2-mymodule.tf
Labels: minor, chore

#2 Adds mq configuration
  main.tf
  outputs.tf
Labels: enhancement, minor

#3 Adds values for mq license and version
  main.tf
Labels: enhancement, patch

#4 Adds ace content
  main.tf
Labels: enhancement, minor

#5 Outputs ace values
  outputs.tf
Labels: bug, patch

#6 Adds apic configuration
  main.tf
  outputs.tf
Labels: enhancement, minor

#7 Adds apic version
  main.tf
Labels: enhancement, patch

#8 updated the dependency for event streams
  main.tf
Labels: enhancement, minor
